name: sleepy
description: this workflow is kinda slow, and might fail

run-name: sleepy ${{ inputs.unique_id }}

on:
  workflow_dispatch:
    inputs:
      unique_id:
        type: string
        required: true
      should_fail:
        type: boolean
        required: false
        default: false

  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      repo:
        type: string
      should_fail:
        type: boolean
        required: false
        default: false
      # TODO: validate these
      source_branch:
        type: string
        required: true
      dest_branch:
        type: string
        required: true
      prev_version: # previous version, to create a changelog from
        type: string
        required: false
    outputs:
      version:
        description: 'destination branch, regurgitated'
        value: ${{ jobs.sleepy.outputs.dest }}

jobs:
  sleepy:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.repo.outputs.repo }}
      dest: ${{ steps.branches.outputs.dest }}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.gh_token }}
      - name: check repo
        id: repo
        run: |-
          cat repo
          echo "repo=$(cat repo)" >> "$GITHUB_OUTPUT"
      - name: branches
        if: ${{ inputs.dest_branch != '' }}
        id: branches
        run: |-
          echo "source: ${{ inputs.source_branch }}"
          echo "dest: ${{ inputs.dest_branch }}"
          echo "dest=${{ inputs.dest_branch }}" >> "$GITHUB_OUTPUT"
      - name: set up artifact
        if: ${{ inputs.dest_branch != '' }}
        id: art
        # artifact names can't have '/' in them,
        # and our release branches have 'release/' on the front
        # Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
        run: |-
          f="$(sed 's~release/~~g' <<< '${{ inputs.dest_branch }}')"
          echo "$(cat repo) : ${{ inputs.repo }} - ${{ inputs.source_branch }} - ${{ inputs.dest_branch }} - ${{ inputs.prev_version}}" > "$f"
          echo "name=$f" >> "$GITHUB_OUTPUT"
      - name: upload artifact
        if: ${{ inputs.dest_branch != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: sleepy-${{ steps.art.outputs.name }}
          path: ${{ steps.art.outputs.name }}
          compression-level: 0
      - name: sleep
        run: sleep 10
      - name: maybe fail
        if: ${{ inputs.should_fail }}
        run: exit 1

