name: sleepy
description: this workflow is kinda slow, and might fail

run-name: sleepy ${{ inputs.unique_id }}

on:
  workflow_dispatch:
    inputs:
      unique_id:
        type: string
        required: true
      should_fail:
        type: boolean
        required: false
        default: false
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      repo:
        type: string
      should_fail:
        type: boolean
        required: false
        default: false
      # TODO: validate these
      source_branch:
        type: string
        required: true
      dest_branch:
        type: string
        required: true
    outputs:
      version: ${{ inputs.dest_branch }}

jobs:
  sleepy:
    if: ${{ inputs.source_branch != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.gh_token }}
      - name: check repo
        run: cat repo
      - name: branches
        run: |-
          echo "source: ${{ inputs.source_branch }}"
          echo "dest: ${{ inputs.dest_branch }}"
      - name: sleep
        run: sleep 30
      - name: maybe fail
        if: ${{ inputs.should_fail }}
        run: exit 1

