name: sleepy
description: this workflow is kinda slow, and might fail

run-name: sleepy ${{ inputs.unique_id }}

on:
  workflow_dispatch:
    inputs:
      unique_id:
        type: string
        required: true
      should_fail:
        type: boolean
        required: true
  workflow_call:
    inputs:
      unique_id:
        type: string
        required: true
      should_fail:
        type: boolean
        required: true

jobs:
  sleepy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: check repo
        run: cat repo
      - name: sleep
        run: sleep 120
      - name: maybe fail
        if: ${{ inputs.should_fail }}
        run: exit 1

